# Use official ROS 2 Foxy base image for ARM64 (Raspberry Pi 5)
FROM arm64v8/ros:foxy

# Install system dependencies for lgpio and gpiod
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     swig \    
#     python3-pip \
#     python3-dev \
#     python3-setuptools \
#     libgpiod2 \
#     libgpiod-dev \
#     build-essential \
#     && rm -rf /var/lib/apt/lists/*


RUN apt-get update && apt-get install -y \
    liblgpio-dev swig build-essential python3 python3-pip


# Install lgpio python bindings via pip
RUN pip3 install lgpio